# Generated by Django 5.1.4 on 2024-12-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва забруднюючої речовини', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Опис забруднюючої речовини', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(help_text="Назва об'єкта", max_length=100)),
                ('volume', models.FloatField(help_text="Об'єм викидів у тоннах")),
                ('date', models.DateField(help_text='Дата викиду')),
                ('pollutant', models.ForeignKey(help_text='Забруднююча речовина', on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(help_text='Ставка податку за 1 тонну (грн)')),
                ('pollutant', models.ForeignKey(help_text='Забруднююча речовина', on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant')),
            ],
        ),
    ]
