# Generated by Django 5.1.4 on 2024-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255, verbose_name="Назва об'єкта")),
                ('pollutant_name', models.CharField(max_length=255, verbose_name='Назва забруднюючої речовини')),
                ('emission_volume', models.FloatField(verbose_name="Об'єм викидів")),
                ('tax_rate', models.FloatField(verbose_name='Ставка податку')),
                ('tax_sum', models.FloatField(verbose_name='Сума податку')),
                ('tax_type', models.CharField(choices=[('air_emissions', 'Викиди в атмосферу'), ('water_discharge', 'Скиди у водні об’єкти'), ('waste_disposal', 'Розміщення відходів'), ('radioactive_waste', 'Утворення радіоактивних відходів'), ('temporary_storage', 'Тимчасове зберігання радіоактивних відходів')], max_length=50, verbose_name='Тип податку')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата розрахунку')),
            ],
        ),
    ]
