# Generated by Django 5.1.4 on 2024-12-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_taxcalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='volume',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='emission_volume',
            field=models.FloatField(default=0, verbose_name="Об'єм викидів"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='date',
            field=models.DateField(verbose_name='Дата викиду'),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='object_name',
            field=models.CharField(max_length=255, verbose_name="Назва об'єкта"),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='emission_volume',
            field=models.FloatField(default=0, verbose_name="Об'єм викидів"),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='tax_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сума податку'),
        ),
    ]
