# Generated by Django 5.1.4 on 2024-12-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_pollutant_pollutionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutionrecord',
            name='pollutant',
            field=models.CharField(max_length=100),
        ),
    ]
