# Generated by Django 5.1.4 on 2024-12-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0006_alter_emissionrecord_emission_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='emission_volume',
            field=models.FloatField(verbose_name="Об'єм викидів (тонн)"),
        ),
    ]
