# Generated by Django 5.1.4 on 2024-12-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0007_alter_emissionrecord_emission_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='pollutant',
            field=models.CharField(max_length=255, verbose_name='Забруднююча речовина'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.FloatField(verbose_name='Ставка податку (грн за тонну)'),
        ),
    ]
