# Generated by Django 5.1.4 on 2024-12-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0013_emergencyevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissionrecord',
            name='pollutant_name',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='pollutant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
    ]
