# Generated by Django 5.1.4 on 2024-12-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0014_remove_emissionrecord_pollutant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculation',
            name='tax_type',
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='emission_volume',
            field=models.FloatField(default=0, verbose_name="Об'єм викидів (тонн)"),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='tax_rate',
            field=models.FloatField(verbose_name='Ставка податку (грн/тонна)'),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='tax_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Сума податку (грн)'),
        ),
    ]
