# Generated by Django 5.1.4 on 2024-12-24 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0016_pollutionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
    ]
