# Generated by Django 5.1.4 on 2024-12-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0017_alter_emissionrecord_pollutant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pollutant',
            table='eco_pollutant',
        ),
    ]
