# Generated by Django 5.1.4 on 2024-12-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0018_alter_pollutant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculation',
            name='pollutant_name',
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='pollutant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='emission_volume',
            field=models.FloatField(verbose_name="Об'єм викидів (тонн)"),
        ),
    ]
