# Generated by Django 5.1.4 on 2024-12-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0019_remove_taxcalculation_pollutant_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollutantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва речовини')),
                ('hazard_class', models.CharField(max_length=50, verbose_name='Клас небезпеки')),
                ('mpc', models.FloatField(blank=True, null=True, verbose_name='ГДК (мг/м³)')),
                ('rfc', models.FloatField(blank=True, null=True, verbose_name='RFC - безпечний рівень впливу речовини')),
                ('sf', models.FloatField(blank=True, null=True, verbose_name='SF - фактор канцерогенного потенціалу')),
                ('specific_emissions', models.FloatField(blank=True, null=True, verbose_name='Питомий показник викиду (qi)')),
                ('tax_rate', models.FloatField(blank=True, null=True, verbose_name='Ставка податку (Сп)')),
                ('hazard_coefficient', models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт класу небезпеки (Кнеб)')),
                ('kn', models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт небезпечності (Кн)')),
            ],
        ),
    ]
