# Generated by Django 5.1.4 on 2024-12-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0020_pollutantdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutant',
            name='description',
        ),
        migrations.AddField(
            model_name='pollutant',
            name='hazard_class',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Клас небезпеки'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='hazard_coefficient',
            field=models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт класу небезпеки (Кнеб)'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='kn',
            field=models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт небезпечності (Кн)'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='mpc',
            field=models.FloatField(blank=True, null=True, verbose_name='ГДК (мг/м³)'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='rfc',
            field=models.FloatField(blank=True, null=True, verbose_name='RFC - безпечний рівень впливу речовини'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='sf',
            field=models.FloatField(blank=True, null=True, verbose_name='SF - фактор канцерогенного потенціалу'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='specific_emissions',
            field=models.FloatField(blank=True, null=True, verbose_name='Питомий показник викиду (qi)'),
        ),
        migrations.AddField(
            model_name='pollutant',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка податку (Сп)'),
        ),
        migrations.AlterField(
            model_name='pollutant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва речовини'),
        ),
        migrations.AlterModelTable(
            name='pollutant',
            table=None,
        ),
    ]
