# Generated by Django 5.1.4 on 2024-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0021_remove_pollutant_description_pollutant_hazard_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutant',
            name='hazard_class',
            field=models.CharField(choices=[('I', 'І клас (надзвичайно небезпечні)'), ('II', 'ІІ клас (високонебезпечні)'), ('III', 'ІІІ клас (помірно небезпечні)'), ('IV', 'IV клас (малонебезпечні)')], default='IV', max_length=50, verbose_name='Клас небезпеки'),
        ),
    ]
