# Generated by Django 5.1.4 on 2024-12-24 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0023_remove_pollutant_hazard_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantdetails',
            name='kn',
        ),
        migrations.RemoveField(
            model_name='pollutantdetails',
            name='tax_rate',
        ),
    ]
