# Generated by Django 5.1.4 on 2024-12-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0024_remove_pollutantdetails_kn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantdetails',
            name='kn',
            field=models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт небезпечності (Кн)'),
        ),
        migrations.AddField(
            model_name='pollutantdetails',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка податку (Сп)'),
        ),
        migrations.AlterField(
            model_name='pollutantdetails',
            name='hazard_class',
            field=models.CharField(max_length=50, verbose_name='Клас небезпеки'),
        ),
    ]
