# Generated by Django 5.1.4 on 2024-12-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0025_pollutantdetails_kn_pollutantdetails_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollutantdetails',
            name='hazard_class',
            field=models.CharField(choices=[('I', 'І клас (надзвичайно небезпечні)'), ('II', 'ІІ клас (високонебезпечні)'), ('III', 'ІІІ клас (помірно небезпечні)'), ('IV', 'IV клас (малонебезпечні)')], default='IV', max_length=50, verbose_name='Клас небезпеки'),
        ),
    ]
