# Generated by Django 5.1.4 on 2024-12-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0027_damagerecord_emission_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255, verbose_name="Назва об'єкта")),
                ('pollutant_name', models.CharField(max_length=255, verbose_name='Назва забруднюючої речовини')),
                ('report_year', models.IntegerField(verbose_name='Рік звітності')),
                ('emission_volume', models.FloatField(verbose_name="Об'єм викидів (т/рік)")),
                ('mass_flow_rate', models.FloatField(verbose_name='Масова витрата (г/с)')),
                ('concentration', models.FloatField(verbose_name='Концентрація сполук у повітрі (мг/м³)')),
                ('hq_coefficient', models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт неканцерогенного ризику (HQ)')),
                ('cr_coefficient', models.FloatField(blank=True, null=True, verbose_name='Коефіцієнт канцерогенного ризику (CR)')),
                ('tax_rate', models.FloatField(verbose_name='Ставка податку (грн/т)')),
                ('tax_sum', models.FloatField(blank=True, null=True, verbose_name='Сума податку (грн)')),
                ('damage_sum', models.FloatField(blank=True, null=True, verbose_name='Сума збитків (грн)')),
            ],
        ),
    ]
