# Generated by Django 5.1.4 on 2024-12-25 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0028_environmentaldamage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentaldamage',
            name='pollutant_name',
        ),
        migrations.AddField(
            model_name='environmentaldamage',
            name='pollutant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
        migrations.AddField(
            model_name='environmentaldamage',
            name='tax_type',
            field=models.CharField(choices=[('air_emissions', 'Викиди в атмосферу'), ('water_discharge', 'Скиди у водні об’єкти'), ('waste_disposal', 'Розміщення відходів'), ('radioactive_waste', 'Утворення радіоактивних відходів'), ('temporary_storage', 'Тимчасове зберігання радіоактивних відходів')], default='air_emissions', max_length=50, verbose_name='Тип податку'),
        ),
    ]
