# Generated by Django 5.1.4 on 2024-12-25 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0029_remove_environmentaldamage_pollutant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentaldamage',
            name='cr_coefficient',
        ),
        migrations.RemoveField(
            model_name='environmentaldamage',
            name='hq_coefficient',
        ),
        migrations.RemoveField(
            model_name='environmentaldamage',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='environmentaldamage',
            name='tax_sum',
        ),
        migrations.AddField(
            model_name='environmentaldamage',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площа впливу (м²)'),
        ),
        migrations.AddField(
            model_name='environmentaldamage',
            name='human_losses',
            field=models.FloatField(blank=True, null=True, verbose_name='Втрати трудових ресурсів'),
        ),
        migrations.AddField(
            model_name='environmentaldamage',
            name='infrastructure_losses',
            field=models.FloatField(blank=True, null=True, verbose_name='Руйнування основних фондів'),
        ),
        migrations.AlterField(
            model_name='environmentaldamage',
            name='concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='Концентрація сполук у повітрі (мг/м³)'),
        ),
        migrations.AlterField(
            model_name='environmentaldamage',
            name='emission_volume',
            field=models.FloatField(blank=True, null=True, verbose_name="Об'єм викидів (т/рік)"),
        ),
        migrations.AlterField(
            model_name='environmentaldamage',
            name='mass_flow_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Масова витрата (г/с)'),
        ),
        migrations.AlterField(
            model_name='environmentaldamage',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
        migrations.AlterField(
            model_name='environmentaldamage',
            name='tax_type',
            field=models.CharField(choices=[('land_pollution', 'Забруднення землі'), ('water_pollution', 'Забруднення води'), ('air_pollution', 'Забруднення повітря'), ('human_health', 'Втрати життя та здоров’я населення'), ('infrastructure_damage', 'Руйнування основних фондів')], max_length=50, verbose_name='Тип збитків'),
        ),
    ]
