# Generated by Django 5.1.4 on 2024-12-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0030_remove_environmentaldamage_cr_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcalculation',
            name='tax_type',
            field=models.CharField(choices=[('air', 'За викиди в атмосферне повітря'), ('water', 'За скиди у водні об’єкти'), ('waste', 'За розміщення відходів'), ('radioactive', 'За утворення радіоактивних відходів'), ('temporary', 'За тимчасове зберігання радіоактивних відходів')], default='air', max_length=50, verbose_name='Тип податку'),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='emission_volume',
            field=models.FloatField(blank=True, null=True, verbose_name="Об'єм викидів (тонн)"),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='pollutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.pollutant', verbose_name='Забруднююча речовина'),
        ),
        migrations.AlterField(
            model_name='taxcalculation',
            name='tax_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка податку (грн/тонна)'),
        ),
    ]
