# Generated by Django 5.1 on 2024-12-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0031_taxcalculation_tax_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagerecord',
            name='damage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сума збитків (грн)'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='damage_type',
            field=models.CharField(choices=[('Air', 'Викиди в атмосферу'), ('Water', 'Скиди у водні об’єкти'), ('Soil', 'Забруднення ґрунту'), ('Radioactive', 'Радіоактивні відходи'), ('Temporary', 'Тимчасове зберігання відходів')], max_length=255, verbose_name='Тип завданої шкоди'),
        ),
    ]
